### ISSUE TITLE
Native Google Cloud Platform (GCP) Support

### ISSUE THREAD

**Issue by namanjain** [coinbase/chainstorage#90]
We’ve been running Chainstorage on AWS and it’s been working out great so far. However, most of our infrastructure is on GCP. It would be great if Chainstorage could natively support GCP in addition to AWS. Are there any such plans in the pipeline? It would be a game changer for us and also expand its usability for a broader audience.

If there is any room for collaboration, we are open to contributing to the codebase and documentation.

**Comment by leozc** [comment]
@bestmike007  is working on this

**Comment by bestmike007** [comment]
@namanjain it's WIP, not production ready but you can give it a try with the following config:

```yaml
storage_type:
  meta: FIRESTORE
  blob: GCS
  dlq: FIRESTORE
aws:
  local_stack: false
gcp:
  project: your-chainstorage-project
  bucket: your-chainstorage-blob-bucket
```

You can use the ADC to authenticate the chainstorage processes. The default firestore database and one GCS bucket is required, and the firestore database can be configured using the firebase cli with the configurations in https://github.com/coinbase/chainstorage/tree/master/scripts/firebase

Documents will be updated later, and we welcome all kinds of contributions.
